name: Process Videos

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["YT 2"]
    types: [completed]

jobs:
  process:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - uses: actions/checkout@v4

      # tải toàn bộ artifact từ workflow trước
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: all_videos

      - name: Install FFmpeg + tool
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          pip install video-music-remover

      - name: Health check
        run: video-music-remover health-check

      - name: Process videos (parallel)
        run: |
          mkdir output
          find all_videos -type f \( -name "*.mp4" -o -name "*.mkv" -o -name "*.webm" \) > list.txt

          cat list.txt | xargs -I {} -P $(nproc) bash -c '
            video-music-remover remove-music "{}" output/ --delete-original
          '

      - name: Upload processed videos
        uses: actions/upload-artifact@v4
        with:
          name: processed_videos
          path: output
